[[constraint]]
  name = "k8s.io/cli-runtime"
  source = "github.com/kubernetes/cli-runtime"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.03.2-ce"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[override]]
  name = "github.com/docker/docker"
  revision = "7848b8beb9d38a98a78b75f78e05f8d2255f9dfe"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"
